import { Injectable, GatewayTimeoutException, InternalServerErrorException } from '@nestjs/common';
import PDFDocument = require('pdfkit');

export interface PdfPageOptions {
  title: string;
  subtitle?: string;
  schoolName?: string;
  exportTimestamp: Date;
}

/**
 * PdfBuilder creates A4 portrait PDF buffers using pdfkit.
 *
 * - Helvetica built-in font, 50pt margins on all sides
 * - Title block: school name (if provided), export title, generated date
 * - Footer injected on every page via the `pageAdded` event
 * - 60-second timeout via Promise.race; throws GatewayTimeoutException on timeout
 * - Never returns a partial buffer — only resolves after the `end` event fires
 */
@Injectable()
export class PdfBuilder {
  /**
   * Creates a PDF document and returns the completed Buffer.
   *
   * @param options  Page-level metadata (title, subtitle, schoolName, exportTimestamp)
   * @param buildFn  Caller-supplied function that adds content to the PDFDocument
   * @returns        Resolved Buffer once the PDF stream has fully ended
   * @throws         GatewayTimeoutException if generation exceeds 60 seconds
   * @throws         InternalServerErrorException on any pdfkit stream error
   */
  async build(
    options: PdfPageOptions,
    buildFn: (doc: PDFKit.PDFDocument) => void,
  ): Promise<Buffer> {
    let timeoutId: ReturnType<typeof setTimeout> | undefined;
    try {
      return await Promise.race([
        this._generate(options, buildFn),
        new Promise<never>((_, reject) => {
          timeoutId = setTimeout(
            () => reject(new GatewayTimeoutException('PDF generation exceeded 60 seconds')),
            60_000,
          );
        }),
      ]);
    } finally {
      if (timeoutId !== undefined) {
        clearTimeout(timeoutId);
      }
    }
  }

  // ─────────────────────────────────────────────────────────────────────────────
  // Private helpers
  // ─────────────────────────────────────────────────────────────────────────────

  private async _generate(
    options: PdfPageOptions,
    buildFn: (doc: PDFKit.PDFDocument) => void,
  ): Promise<Buffer> {
    return new Promise<Buffer>((resolve, reject) => {
      const doc = new PDFDocument({
        size: 'A4',
        layout: 'portrait',
        margins: { top: 50, bottom: 50, left: 50, right: 50 },
        autoFirstPage: false,
      });

      const chunks: Buffer[] = [];

      doc.on('data', (chunk: Buffer) => chunks.push(chunk));

      doc.on('end', () => {
        resolve(Buffer.concat(chunks));
      });

      doc.on('error', (err: Error) => {
        reject(new InternalServerErrorException(`PDF generation failed: ${err.message}`));
      });

      // Register footer injection before adding the first page so the
      // `pageAdded` event fires for every page including the first one.
      doc.on('pageAdded', () => {
        this.addFooter(doc, options.exportTimestamp);
      });

      // Add the first page — this triggers `pageAdded` immediately.
      doc.addPage();

      // Render title block
      this._addTitleBlock(doc, options);

      // Let the caller add content
      buildFn(doc);

      doc.end();
    });
  }

  /**
   * Renders the standard title block at the current cursor position.
   * Leaves the cursor positioned below the title block ready for content.
   */
  private _addTitleBlock(doc: PDFKit.PDFDocument, options: PdfPageOptions): void {
    const { title, subtitle, schoolName, exportTimestamp } = options;

    // School name (largest)
    if (schoolName) {
      doc
        .font('Helvetica-Bold')
        .fontSize(18)
        .text(schoolName, { align: 'center' });
      doc.moveDown(0.4);
    }

    // Export title
    doc
      .font('Helvetica-Bold')
      .fontSize(14)
      .text(title, { align: 'center' });

    // Optional subtitle
    if (subtitle) {
      doc.moveDown(0.3);
      doc
        .font('Helvetica')
        .fontSize(11)
        .text(subtitle, { align: 'center' });
    }

    // Generated date
    const dateLabel = `Generated: ${this._formatTimestamp(exportTimestamp)}`;
    doc.moveDown(0.3);
    doc
      .font('Helvetica')
      .fontSize(9)
      .fillColor('#666666')
      .text(dateLabel, { align: 'center' });

    // Reset fill colour and add some vertical space before content
    doc.fillColor('#000000').moveDown(1);
  }

  /**
   * Adds the footer to the current page.
   *
   * Called inside the `pageAdded` event so it fires for every page.
   * The footer is placed at the bottom of the printable area (page height
   * minus the bottom margin) without disturbing the current cursor position
   * used by the main content.
   */
  private addFooter(doc: PDFKit.PDFDocument, timestamp: Date): void {
    const pageWidth = doc.page.width;
    const bottomMargin = doc.page.margins.bottom;
    const footerY = doc.page.height - bottomMargin - 12;

    const footerText = `Generated by Myschoolbud  |  ${this._formatTimestamp(timestamp)}`;

    // Save the current cursor state so content rendering is unaffected
    const savedY = doc.y;

    doc
      .font('Helvetica')
      .fontSize(8)
      .fillColor('#999999')
      .text(footerText, doc.page.margins.left, footerY, {
        width: pageWidth - doc.page.margins.left - doc.page.margins.right,
        align: 'center',
        lineBreak: false,
        height: 12,
      });

    // Restore fill colour and cursor
    doc.fillColor('#000000');
    doc.y = savedY;
  }

  /**
   * Formats a Date as `YYYY-MM-DD HH:mm UTC`.
   */
  private _formatTimestamp(date: Date): string {
    const pad = (n: number): string => String(n).padStart(2, '0');
    const year = date.getUTCFullYear();
    const month = pad(date.getUTCMonth() + 1);
    const day = pad(date.getUTCDate());
    const hours = pad(date.getUTCHours());
    const minutes = pad(date.getUTCMinutes());
    return `${year}-${month}-${day} ${hours}:${minutes} UTC`;
  }
}
