/**
 * One-time global backfill: queue all KnowledgeChunk rows with null embedding
 * for background embedding generation (BullMQ → VectorProcessor → OpenAI).
 *
 * Use when you already have Postgres data before enabling the vector pipeline.
 * After this, new/updated data is handled by the queue on create/update.
 *
 * Run from backend root:
 *   npm run backfill-embeddings
 *
 * Requires: DB_URL, REDIS_URL (or REDIS_HOST+REDIS_PORT). Embeddings are
 * generated by the running app's VectorProcessor when it processes the queue.
 */

import { PrismaClient } from '@prisma/client';
import { Queue } from 'bullmq';
import * as path from 'path';
import * as fs from 'fs';

const VECTOR_QUEUE_NAME = '{vector}';
const JOB_GENERATE_EMBEDDING = 'generate-embedding';

// Load .env from backend root
const envPath = path.join(__dirname, '..', '.env');
if (fs.existsSync(envPath)) {
  const content = fs.readFileSync(envPath, 'utf-8');
  for (const line of content.split('\n')) {
    const m = line.match(/^\s*([^#=]+)=(.*)$/);
    if (m) process.env[m[1].trim()] = m[2].trim().replace(/^["']|["']$/g, '');
  }
}

function getRedisConnection(): any {
  const url = process.env.REDIS_URL;
  if (url) return url;
  const host = process.env.REDIS_HOST || 'localhost';
  const port = parseInt(process.env.REDIS_PORT || '10000', 10);
  const password = process.env.REDIS_PASSWORD;
  const tls = process.env.REDIS_TLS === 'true';
  return {
    host,
    port,
    password,
    tls: tls ? {} : undefined,
  };
}

async function main() {
  if (!process.env.DB_URL) {
    console.error('DB_URL is not set. Set it in .env and run from backend root.');
    process.exit(1);
  }

  const redis = getRedisConnection();
  if (!redis) {
    console.error('REDIS_URL or REDIS_HOST must be set.');
    process.exit(1);
  }

  console.log('Backfill: connecting to DB...');
  const prisma = new PrismaClient();

  try {
    const chunks = await prisma.$queryRawUnsafe<{ id: string }[]>(
      `SELECT id FROM "KnowledgeChunk" WHERE embedding IS NULL AND content IS NOT NULL AND trim(content) != ''`,
    );

    console.log(`Backfill: found ${chunks.length} chunk(s) with null embedding.`);

    if (chunks.length === 0) {
      console.log('No chunks need backfill (all have embeddings or empty content).');
      return;
    }

    const queue = new Queue(VECTOR_QUEUE_NAME, {
      connection: redis as any,
      defaultJobOptions: {
        attempts: 5,
        backoff: { type: 'exponential', delay: 2000 },
      },
    });

    try {
      let queued = 0;
      for (const row of chunks) {
        try {
          await queue.add(JOB_GENERATE_EMBEDDING, { chunkId: row.id }, { jobId: row.id });
          queued++;
        } catch (e) {
          console.warn(`Failed to queue chunk ${row.id}:`, (e as Error).message);
        }
      }
      console.log(`Done. Queued ${queued} chunk(s) for embedding generation.`);
    } finally {
      await queue.close();
    }
  } finally {
    await prisma.$disconnect();
  }

  process.exit(0);
}

main().catch((err) => {
  console.error('Backfill failed:', err);
  process.exit(1);
});
